name: bd_gov_mochta_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hive:
  hive_flutter:
  animated_button_bar: ^0.0.2
  image_picker: ^0.8.4+11
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  get: 4.6.5
  flutter_wizard: ^2.0.5
  flutter: 
    sdk: flutter
  sqflite: ^2.0.3+1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  hive_generator:
  build_runner:

flutter: 



  uses-material-design: true

